name: CI
on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Descargando el codigo
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Instalar Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compilar
        run: ./gradlew build
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: danielsabana/my-tech
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: danielsabana
          password: ${{ secrets.DOCKER_PASSWORD }}
