name: CI
on:
  pull_request:
    branches:
      - develop
      - master
      - release
      - main
permissions:
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Descargando el codigo
      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Instalar Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compilar
        run: ./gradlew build
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew testCoverage
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          min-coverage-overall: 40
          min-coverage-changed-files: 60
